### ISSUE TITLE
Problem with 1.7.10 servers

### ISSUE THREAD

**Issue by IvanTabakerka** [LKxth/minecraft-java-server-query#2]
```
/home/container/node_modules/minecraft-java-server-query/lib/motd.js:36
    if (motd.color) {
             ^
TypeError: Cannot read properties of undefined (reading 'color')
    at toRaw (/home/container/node_modules/minecraft-java-server-query/lib/motd.js:36:14)
    at /home/container/node_modules/minecraft-java-server-query/lib/index.js:91:44
    at Generator.next (<anonymous>)
    at fulfilled (/home/container/node_modules/minecraft-java-server-query/lib/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v20.18.0
```

**Comment by justcarlux** [comment]
hey! i updated the library with the new fixes. update it to the latest version and try again
